### PR TITLE
Add constraint: Cabal >= 3.0.

### LINKED ISSUE #27: Build error: "No instance for (Distribution.Text.Text LiLicence)"
```
falsifian angel licensor $ cabal build .
Resolving dependencies...
Build profile: -w ghc-8.6.4 -O1
In order, the following will be built (use -v for more details):
 - licensor-0.4.1 (lib) (configuration changed)
 - licensor-0.4.1 (exe:licensor) (configuration changed)
Configuring library for licensor-0.4.1..
Preprocessing library for licensor-0.4.1..
Building library for licensor-0.4.1..
[2 of 2] Compiling Licensor         ( src/Licensor.hs, /home/falsifian/src/licensor/dist-newstyle/build/x86_64-
openbsd/ghc-8.6.4/licensor-0.4.1/build/Licensor.o )

src/Licensor.hs:69:15: error:
    • No instance for (Distribution.Text.Text LiLicense)
        arising from a use of ‘display’
    • In the first argument of ‘comparing’, namely ‘display’
      In the expression: comparing display
      In an equation for ‘compare’: compare = comparing display
   |
69 |     comparing display
   |               ^^^^^^^
cabal: Failed to build licensor-0.4.1 (which is required by exe:licensor from
licensor-0.4.1).
```

I suspect it's because cabal is trying to use version 2 of the Cabal library. I'm currently trying with a version restriction `>= 3.0` added for `Cabal` and will send a pull request if it works.

### PR DESCRIPTION
**Pull request by falsifian**
I haven't researched exactly what the constraint should be, but 3.2.1.0
works for me.

Without this, I got the following, probably caused by trying to build
with Cabal 2 installed:

src/Licensor.hs:69:15: error:
    • No instance for (Distribution.Text.Text LiLicense)
        arising from a use of ‘display’
    • In the first argument of ‘comparing’, namely ‘display’
      In the expression: comparing display
      In an equation for ‘compare’: compare = comparing display

Fixes #27.

### CODE REVIEW

**Review by jpvillaisaza — APPROVED** [review]

**Comment by jpvillaisaza** [comment]
Thanks! I was able to build using Cabal 3.0.0.0.
